# Generated by Django 2.2 on 2019-05-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190517_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(default='', max_length=20)),
                ('player2', models.CharField(default='', max_length=20)),
                ('winner', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
