# Generated by Django 2.2 on 2019-05-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=20),
        ),
    ]
