# Generated by Django 2.2 on 2019-05-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todos',
        ),
    ]
